# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    csrf_protection:
        enabled: false


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
            handler_id: session.handler.mock_file
            save_path: '%kernel.project_dir%/var/sessions/test'