# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session:
        cookie_secure: true
        cookie_samesite: lax
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        # Remove storage_id and use storage_factory_id only if needed
        name: app_session
        cookie_lifetime: 3600

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
            handler_id: session.handler.mock_file
            save_path: '%kernel.project_dir%/var/sessions/test'