security:
    password_hashers:
        Infrastructure\Symfony\Security\SecurityUser:
            algorithm: auto
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto    
    providers:
        app_user_provider:
            id: Infrastructure\Symfony\Security\UserProvider
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            entry_point: Infrastructure\Symfony\Security\AuthenticationEntryPoint
            custom_authenticator: Infrastructure\Symfony\Security\FormLoginAuthenticator
            logout:
                path: app_logout
                target: app_security
            
            # Disable unused authentication methods
            form_login: false
            http_basic: false
            
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/dashboard, roles: [ROLE_USER, ROLE_ADMIN] }

when@test:
    security:
        password_hashers:
            Domain\User\Gateway\UserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon