services:
    _defaults:
        autowire: true
        autoconfigure: true

    Domain\:
        resource: '../src/Domain/'
        exclude:
            - '../src/Domain/*/Data/Model'
            - '../src/Domain/*/Data/Enum'
            - '../src/Domain/*/Test'

    Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/Symfony/Kernel.php'
            - '../src/Infrastructure/Database/Entity/'

    Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/**/*'
        tags: ['controller.service_arguments']
        
    Infrastructure\Symfony\Security\:
        resource: '../src/Infrastructure/Symfony/Security/'
    

    Domain\User\Gateway\PasswordHasherInterface:
        alias: Infrastructure\Symfony\Security\SymfonyPasswordHasher

    Infrastructure\Symfony\Security\SymfonyPasswordHasher:
        arguments: 
            $symfonyPasswordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'