parameters:
    appUrl: '%env(APP_URL)%'
    appEnv: '%env(APP_ENV)%'
    secretKey: '%env(APP_SECRET)%'
    algorithm: '%env(APP_ALGORITHM)%'
    noReplyEmail: '%env(NO_REPLY_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $appUrl: '%appUrl%'
            $appEnv: '%appEnv%'
            $secretKey: '%secretKey%'
            $algorithm: '%algorithm%'
            $noReplyEmail: '%noReplyEmail%'


    Domain\:
        resource: '../src/Domain/'
        exclude:
            - '../src/Domain/*/Data/Model'
            - '../src/Domain/*/Data/Enum'
            - '../src/Domain/*/Test'

    Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/Symfony/Kernel.php'
            - '../src/Infrastructure/Database/Entity/'

    Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/**/*'
        tags: ['controller.service_arguments']
        
    Infrastructure\Symfony\Security\:
        resource: '../src/Infrastructure/Symfony/Security/'
    

    Domain\User\Gateway\PasswordHasherInterface:
        alias: Infrastructure\Symfony\Security\SymfonyPasswordHasher

    Infrastructure\Symfony\Security\SymfonyPasswordHasher:
        arguments: 
            $symfonyPasswordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    Domain\User\Gateway\AuthenticationManagerInterface:
        class: Infrastructure\Symfony\Security\SymfonyAuthenticationManager
        arguments:
            $userAuthenticator: '@Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface'
            $authenticator: '@Infrastructure\Symfony\Security\FormLoginAuthenticator'
     
    #Domain\User\Service\TokenServiceInterface: '@Infrastructure\Symfony\Services\Jwt\JWTTokenService'

    Infrastructure\Database\Fixture\UsersFixture:
        tags: ['doctrine.fixture.orm']
        