parameters:
    appUrl: '%env(APP_URL)%'
    appEnv: '%env(APP_ENV)%'
    secretKey: '%env(APP_SECRET)%'
    algorithm: '%env(APP_ALGORITHM)%'
    noReplyEmail: '%env(NO_REPLY_EMAIL)%'
    mailerService: '%env(MAILER_SERVICE)%'
    publicDirectory: '%kernel.project_dir%/public'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $appUrl: '%appUrl%'
            $appEnv: '%appEnv%'
            $secretKey: '%secretKey%'
            $algorithm: '%algorithm%'
            $noReplyEmail: '%noReplyEmail%'
            $mailerService: '%mailerService%'
            $publicDirectory: '%publicDirectory%'

    Infrastructure\Symfony\Services\Email\DefaultEmailSender:
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'
            $twig: '@Twig\Environment'
    Domain\:
        resource: '../src/Domain/'
        exclude:
            - '../src/Domain/*/Data/Model'
            - '../src/Domain/*/Data/Enum'
            - '../src/Domain/*/Test'

    Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/Symfony/Kernel.php'
            - '../src/Infrastructure/Database/Entity/'

    Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/**/*'
        tags: ['controller.service_arguments']
        
    Infrastructure\Symfony\Security\:
        resource: '../src/Infrastructure/Symfony/Security/'
    

    Domain\User\Gateway\PasswordHasherInterface:
        alias: Infrastructure\Symfony\Security\SymfonyPasswordHasher
    Infrastructure\Symfony\Security\SymfonyPasswordHasher:
        arguments: 
            $symfonyPasswordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
    Domain\User\Gateway\AuthenticationManagerInterface:
        class: Infrastructure\Symfony\Security\SymfonyAuthenticationManager
        arguments:
            $userAuthenticator: '@Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface'
            $authenticator: '@Infrastructure\Symfony\Security\FormLoginAuthenticator'
    Infrastructure\Symfony\Services\Email\EmailSenderInterface: '@Infrastructure\Symfony\Services\Email\DefaultEmailSender'
    Infrastructure\Symfony\Services\File\SymfonyFileStorageService:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/uploads'
            $publicDir: '/uploads'
    Domain\Shared\Service\File\FileStorageServiceInterface:
        alias: Infrastructure\Symfony\Services\File\SymfonyFileStorageService
    Domain\Document\Service\DocumentDownloaderInterface:
        class: Infrastructure\Symfony\Services\Document\SymfonyDocumentDownloader
    Domain\Document\Service\DocumentDeleteInterface:
        class: Infrastructure\Symfony\Services\Document\SymfonyDocumentDownloader
    

    

    Infrastructure\Database\Fixture\UsersFixture:
        tags: ['doctrine.fixture.orm']
    Infrastructure\Database\Fixture\MachinesFixture:
        tags: ['doctrine.fixture.orm']
        